openshift/cli-manager-operator

Dockerfile.ci
Makefile
bindata/assets/cli-manager/clusterrole.yaml
cmd/cli-manager-operator-testing/main.go
deploy/07_deployment.yaml
hack/install-krew.sh
pkg/cmd/operator/cmd.go
pkg/generated/clientset/versioned/typed/climanager/v1/fake/fake_climanager.go
pkg/operator/starter.go
pkg/operator/target_config_reconciler.go
test/e2e/bindata/assets/00_cli-manager-operator.crd.yaml
test/e2e/bindata/assets/02_config.openshift.io_plugins.yaml
test/e2e/bindata/assets/03_clusterrole.yaml
test/e2e/bindata/assets/06_deployment.yaml
test/e2e/bindata/assets/07_cli-manager-operator-cr.yaml
test/e2e/operator_test.go

WRKLDS-1067: Implement e2e test

---

bindata/assets/cli-manager/clusterrole.yaml
deploy/03_clusterrole.yaml
test/e2e/bindata/assets/03_clusterrole.yaml

[WRKLDS-1287](https://issues.redhat.com/browse/WRKLDS-1287)

WRKLDS-1287: Replace wildcards with an explicit list of verbs

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml
.tekton/cli-manager-operator-pull-request.yaml
.tekton/cli-manager-operator-push.yaml
bundle.Dockerfile

This PR fixes some other violations that Konflux errors out and prevents new release.

WRKLDS-1309: Fix some other violations that prevents new release in Konflux

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml
.tekton/cli-manager-operator-pull-request.yaml
.tekton/cli-manager-operator-push.yaml
bundle.Dockerfile

Preflight checks against bundle image includes some errors and this PR fixes some of them. After this PR, bundle image's preflight checks are passing.

WRKLDS-1309: Fix some of bundle image preflight check failures

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml
.tekton/cli-manager-operator-pull-request.yaml
.tekton/cli-manager-operator-push.yaml

WRKLDS-1309: Run prefetch-dependencies task even hermetic is true

---

bundle.Dockerfile

This PR's main purpose is to trigger new release with this minor fix.

WRKLDS-1309: Fix unclear description

---

bundle.Dockerfile

WRKLDS-1309: Add cli-manager into bundle tags

---

manifests/cli-manager-operator.clusterserviceversion.yaml

WRKLDS-1372: Add operand and operator as related images in CSV

---

Dockerfile
Dockerfile.ci
bundle.Dockerfile
manifests/cli-manager-operator.clusterserviceversion.yaml
metadata/annotations.yaml

WRKLDS-1372: Update descriptions and fix package name

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml
.tekton/cli-manager-operator-pull-request.yaml
.tekton/cli-manager-operator-push.yaml

NO-JIRA: Bump buildah image to 0.2

---

.tekton/cli-manager-operator-fbc-4-17-pull-request.yaml
.tekton/cli-manager-operator-fbc-4-17-push.yaml

NO-JIRA: Rename fbc tekton name from 417 to 4.17

---

Dockerfile

[release-4.17] WRKLDS-1421: Add required image labels in Dockerfile

---

Dockerfile

WRKLDS-1421: Add required image labels in Dockerfile

---

.tekton/cli-manager-operator-fbc-4-17-pull-request.yaml
.tekton/cli-manager-operator-fbc-4-17-push.yaml

WRKLDS-1421: Fix alignment issue in tekton files for fbc

---

manifests/cli-manager-operator.clusterserviceversion.yaml

WRKLDS-1421: Fix rbac typo in endpoints

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml
.tekton/cli-manager-operator-pull-request.yaml
.tekton/cli-manager-operator-push.yaml

WRKLDS-1421: Remove deprecated sbom-json-check task from tekton pipelines

---

Dockerfile
Makefile
bundle.Dockerfile

WRKLDS-1421: Add commit in version and use latest 9.4 rhel image

---

bundle.Dockerfile

Manual backport of https://github.com/openshift/cli-manager-operator/pull/355

NO-JIRA: Use multi arch image pullspec

---

v4.17/catalog/cli-manager/index.yaml

OCPBUGS-42622: Use multi arch operator and operand images

---

v4.17/catalog/cli-manager/index.yaml

NO-JIRA: Update index.yaml with new pullspecs

---

.tekton/cli-manager-operator-fbc-4-17-pull-request.yaml
.tekton/cli-manager-operator-fbc-4-17-push.yaml
v4.17/catalog/cli-manager/index.yaml

NO-JIRA: New release including CA and ProxyURL fields

---

v4.17/catalog/cli-manager/index.yaml

NO-JIRA: Prepare new release

---

bundle.Dockerfile

Change registry name to new domain

---

bundle.Dockerfile

[release-4.17]: Change registry domain url to new one

---

pkg/cmd/operator/cmd.go

NO-JIRA: Make dummy change

---

README.md
v4.17/catalog/cli-manager/index.yaml

NO-JIRA: Migrate to newer image registry domain

---

.ci-operator.yaml
Dockerfile.ci
test/e2e/operator_test.go

NO-JIRA: Use 4.19 image for CI

---

.ci-operator.yaml
.tekton/cli-manager-operator-4-18-pull-request.yaml
.tekton/cli-manager-operator-4-18-push.yaml
.tekton/cli-manager-operator-bundle-4-18-pull-request.yaml
.tekton/cli-manager-operator-bundle-4-18-push.yaml
Dockerfile.ci
test/e2e/operator_test.go

NO-JIRA: Prepare 4.18 branch for new application

---

.tekton/cli-manager-operator-4-18-pull-request.yaml
.tekton/cli-manager-operator-4-18-push.yaml
.tekton/cli-manager-operator-bundle-4-18-pull-request.yaml
.tekton/cli-manager-operator-bundle-4-18-push.yaml

NO-JIRA: Use suggested image url

---

.tekton/cli-manager-operator-fbc-4-18-pull-request.yaml
.tekton/cli-manager-operator-fbc-4-18-push.yaml

NO-JIRA: Use suggested output image

---

.tekton/cli-manager-operator-fbc-4-18-pull-request.yaml
.tekton/cli-manager-operator-fbc-4-18-push.yaml

NO-JIRA: Remove deprecated tasks and use validate-fbc

---

manifests/cli-manager-operator.clusterserviceversion.yaml

Idea is mimicked from https://github.com/openshift/cluster-kube-descheduler-operator/pull/407

NO-JIRA: Add suggested namespace annotation

---

go.mod
go.sum
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/config.go
vendor/golang.org/x/net/http2/config_go124.go
vendor/golang.org/x/net/http2/config_pre_go124.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/unencrypted.go
vendor/golang.org/x/net/http2/write.go
vendor/golang.org/x/net/websocket/websocket.go
vendor/modules.txt

NO-JIRA: Bump go x/net to 1.33

---

bundle.Dockerfile

Use staging repository for testing and nudge update

---

bundle.Dockerfile

NO-JIRA: Use staging instead of production

---

bundle.Dockerfile

NO-JIRA: Use prod registry as a preparation of new release

---

pkg/operator/starter.go

NO-JIRA: Add godoc to trigger a new rebuild

---

v4.17/catalog/cli-manager/index.yaml

NO-IJRA: Update image pullspecs with new release

---

Makefile
bundle.Dockerfile
manifests/cli-manager-operator.clusterserviceversion.yaml

NO-JIRA: Prepare for 0.1.1 release for 4.18

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml
.tekton/cli-manager-operator-pull-request.yaml
.tekton/cli-manager-operator-push.yaml

WRKLDS-1662: Add required Konflux tasks for release

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml

WRKLDS-1662: Remove redundant task from bundle pipeline

---

.tekton/cli-manager-operator-4-18-pull-request.yaml
.tekton/cli-manager-operator-4-18-push.yaml
.tekton/cli-manager-operator-bundle-4-18-pull-request.yaml
.tekton/cli-manager-operator-bundle-4-18-push.yaml

WRKLDS-1662: Remove redundant bundle task

---

.tekton/cli-manager-operator-4-18-pull-request.yaml
.tekton/cli-manager-operator-4-18-push.yaml
.tekton/cli-manager-operator-bundle-4-18-pull-request.yaml
.tekton/cli-manager-operator-bundle-4-18-push.yaml

Trigger pipelinerun to get new snapshot

---

.tekton/cli-manager-operator-fbc-4-18-pull-request.yaml
.tekton/cli-manager-operator-fbc-4-18-push.yaml
v4.18/catalog/cli-manager/index.yaml

WRKLDS-1662: Prepare for 0.1.1 release for 4.18

---

.tekton/cli-manager-operator-bundle-pull-request.yaml
.tekton/cli-manager-operator-bundle-push.yaml
.tekton/cli-manager-operator-pull-request.yaml
.tekton/cli-manager-operator-push.yaml

NO-JIRA: Add required sast tasks

---

.tekton/cli-manager-operator-fbc-4-19-pull-request.yaml
.tekton/cli-manager-operator-fbc-4-19-push.yaml

NO-JIRA: React to changes in apply-tags

---

v4.20/devfile.yaml

NO-JIRA: Trigger build pipeline
