openshift/cli-manager-operator

- Dockerfile
Konflux does not support internal registries and the suggested path is to use brew.registry.redhat.io. This PR incorporates this requirement.
I'd like to note that Dockerfile.ci will continue using internal registries and CI jobs will be run along this path. Dockerfile which is used by Konflux pipeline will use brew.registry.redhat.io. That means, there might be a slight difference with regards to base images between CI and Konflux. However, there might not be any alternative to also overcome this discrepancy.
This is the same change incorporated in https://github.com/openshift/cli-manager/pull/12
> WRKLDS-1295: Use brew registry for Konflux

- Dockerfile
- Dockerfile.ci
This PR applies some changes in order to suppress some warnings that are printed out during Konflux pipeline build.
> WRKLDS-1296: Run with non-root user and copy LICENSE

- Dockerfile
There seems to be a mechanism to update the operand images in operator, when operand's image digest is changed. However, we don't know yet this feature is working properly or even for which image registry it is triggered.
This PR adds some candidate image registries to check which one will be updated. Once the test is done, this PR has to be reverted by leaving the correct image in here.
Once the PR is landed, we are going to merge something in cli-manager repository and expect that the Konflux bot will open a automatic PR to update the digest in one of the images defined in here.
> WRKLDS-1297: Test image auto update

- .tekton/cli-manager-operator-pull-request.yaml
- .tekton/cli-manager-operator-push.yaml
In order to prevent infinite image build invocations, we need to only trigger image builds only when it is required. This PR skips image builds for metadata updates.
> WRKLDS-1297: Skip running Konflux built for some paths

- bundle.Dockerfile
We have to use sha256 based image but as an onboarding process, we don't have it yet. Just to build the bundle dockerfile, we need to use the latest temporarily. Once we have initial bundle image, we should revert back to digest based usage.
> NO-JIRA: Use latest image to allow bundle dockerfile build correctly

- bundle.Dockerfile
This PR modifies the bundle.Dockerfile to correctly copy manifests and metadata directories from builder to build the bundle dockerfile.
> NO-JIRA: Use correct path to copy manifests from builder

- bundle.Dockerfile
This PR uses the correct digest value of cli-manager-operator.
> NO-JIRA: Use correct digest value for cli-manager-operator image

- .tekton/cli-manager-operator-bundle-pull-request.yaml
- .tekton/cli-manager-operator-bundle-push.yaml
`bundle.Dockerfile` should only be built by Konflux when manifests, metadata and bundle.Dockerfile are updated. 
This PR applies the necessary changes enumerated in https://github.com/openshift/cli-manager-operator/pull/23#issuecomment-2154329348
> NO-JIRA: Build bundle dockerfile only manifests metadata is updated

- .tekton/cli-manager-operator-bundle-pull-request.yaml
- .tekton/cli-manager-operator-bundle-push.yaml
- .tekton/cli-manager-operator-pull-request.yaml
- .tekton/cli-manager-operator-push.yaml
This PR adds back to cel expressions. Because the new application configuration overwrote them.
> NO-JIRA: Add back cel expressions to prevent infinite build

- manifests/cli-manager-operator.clusterserviceversion.yaml
`opm index add` fails with incorrect version value because it requires the version should be in major.minor.patch format. This PR fixes this.
> WRKLDS-1309: Fix incorrect csv version value to 0.1.0

- Dockerfile
Previous image's grade is C and Konflux fails in releasing process by throwing an error. This PR uses grade A image.
> WRKLDS-1309: Use grade A image to cover warnings

- Dockerfile
- bundle.Dockerfile
- deploy/03_clusterrole.yaml
- manifests/cli-manager-operator.clusterserviceversion.yaml
Currently, we are replacing operand image in operator image. However, operand image is injected by bundle image. This PR replaces operand and operator image in bundle image. 
Additionally, this PR adds `replicasets` in cluster role permissions as well as some minor improvements in csv file.
> WRKLDS-1309: Replace operand image in bundle image not in operator image

- .tekton/cli-manager-operator-bundle-pull-request.yaml
- .tekton/cli-manager-operator-bundle-push.yaml
- .tekton/cli-manager-operator-pull-request.yaml
- .tekton/cli-manager-operator-push.yaml
This PR defines snyk-secret to run sast-snyk-check job which is required for releasing in Konflux.
> WRKLDS-1309: Add snyk secret to run sast-snyk-check job

- renovate.json
Renovate opens numerous PRs periodically and this is distracting. This PR adds renovate.json to only allow the renovate PRs being opened on Tuesday in each week.
> WRKLDS-1421: Add renovate.json to reduce PRs opened

- .tekton/cli-manager-operator-pull-request.yaml
- .tekton/cli-manager-operator-push.yaml
- deploy/02_config.openshift.io_plugins.yaml
- test/e2e/bindata/assets/02_config.openshift.io_plugins.yaml
To field in Plugin can be defaulted to . where points the default location of Krew. Bin field is no longer required because it can be set to the value of first From field.
> WRKLDS-1421: Add default for To and make Bin as optional

- bindata/assets/cli-manager/deployment.yaml
- bindata/assets/cli-manager/service.yaml
- bindata/assets/cli-manager/servicemonitor.yaml
This PR is complementary of this https://github.com/openshift/cli-manager/pull/92 as operator actually applies the resource configurations.
> WRKLDS-1421: Serve metrics server in https 

- .tekton/cli-manager-operator-4-17-pull-request.yaml
- .tekton/cli-manager-operator-4-17-push.yaml
- .tekton/cli-manager-operator-bundle-4-17-pull-request.yaml
- .tekton/cli-manager-operator-bundle-4-17-push.yaml
- bundle.Dockerfile
release-4.17 branch cut has been performed and there is no more mirroring from main branch. We can update release-4.17 branch for Konflux accordingly.
> WRKLDS-1421: Prepare tekton files specific to release-4.17 branch

- bindata/assets/cli-manager/deployment.yaml
- bindata/assets/cli-manager/servicemetrics.yaml
- bindata/assets/cli-manager/servicemonitor.yaml
- pkg/operator/target_config_reconciler.go
Targetconfig observer expects to apply one resource in each yaml file. That's why, this PR separates metrics service resource to it's own file to apply.
> WRKLDS-1421: Separate metrics service into own file to apply in targetconfig observer

- manifests/cli-manager-operator.clusterserviceversion.yaml
This commit https://github.com/openshift/cli-manager-operator/commit/4b9e131ca63a0e00751af7c0e03f11661483a985#diff-39b9bcfe2dd05e24d533fd24fa9a5860a2ce17bdc188d9dcf9d7be10a9a1512a performed some changes in RBAC. However, it is forgotten to incorporate same changes in CSV file. This PR achieves this.
> WRKLDS-1421: Update CSV according to new rbac changes

- deploy/00_cli-manager-operator.crd.yaml
- manifests/openshift-cli-manager-operator.crd.yaml
- test/e2e/bindata/assets/00_cli-manager-operator.crd.yaml
In order to update the status of climanager CRD, we need to define status subresource in the CRD definition. Otherwise, we get periodic not found errors during the update. This PR fixes this.
> OCPBUGS-39351: Add status subresource for climanager CRD

- bindata/assets/cli-manager/deployment.yaml
- deploy/07_deployment.yaml
- manifests/cli-manager-operator.clusterserviceversion.yaml
- test/e2e/bindata/assets/06_deployment.yaml
This PR sets `readOnlyRootFilesystem` to true for cli manager operator and operand in addition to adding restricted securitycontext configurations for cli manager operator deployment.
> OCPBUGS-41512: Set readOnlyRootFilesystem to true for operator and operand

- .tekton/cli-manager-operator-bundle-pull-request.yaml
- .tekton/cli-manager-operator-bundle-push.yaml
- .tekton/cli-manager-operator-pull-request.yaml
- .tekton/cli-manager-operator-push.yaml
This PR adds multi arch support for cli manager operator by updating it to use new tekton configuration. This PR also reconfigures bundle to still support single arch but using references to new `oci-ta` build pipeline.
> WRKLDS-1491: Add multi arch support for operator and reconfigure bundle

- manifests/cli-manager-operator.clusterserviceversion.yaml
As cli manager now supports multi arch images, we can update CSV to notify users about this.
> WRKLDS-1491: Modify CSV by adding supported other architectures

- .tekton/cli-manager-operator-fbc-4-17-pull-request.yaml
- .tekton/cli-manager-operator-fbc-4-17-push.yaml
There is a bug in pipeline that fails when FBC image is multi arch image list and this will be fixed by https://github.com/konflux-ci/release-service-catalog/pull/559 and releasing to prod will take time. 
In order to unblock cli manager FBC release and continue testing, this PR reverts back to FBC configuration to single arch to get a release. After the release, there will be new PR to add multi arch again.
> WRKLDS-1491: Revert back to single arch temporarily

- .tekton/cli-manager-operator-fbc-4-17-pull-request.yaml
- .tekton/cli-manager-operator-fbc-4-17-push.yaml
This PR switches back to multi arch of FBC that was reverted in https://github.com/openshift/cli-manager-operator/pull/337.
> WRKLDS-1491: Add multi arch FBC support back again

- bundle.Dockerfile
For nudging correctly updates with multi arch instead of amd64.
> NO-JIRA: Use multi arch image pullspec

- manifests/config.openshift.io_plugins.yaml
- test/e2e/bindata/assets/02_config.openshift.io_plugins.yaml
This PR gets the fields defined in https://github.com/openshift/cli-manager/pull/149 into the operator.
> OCPBUGS-42868: Add CABundle and ProxyURL to access image registries

- .tekton/cli-manager-operator-fbc-4-17-pull-request.yaml
- .tekton/cli-manager-operator-fbc-4-17-push.yaml
- .tekton/images-mirror-set.yaml
All products building FBC fragments in Konflux are requested to merge this change irrespective of whether the product is intended for FIPS mode or not.
Beginning March 1, 2025, the fbc-fips-task is going to be a required task in the Konflux
pipeline. This means, your release will be blocked if this task is not present in your pipeline run.
The answer is yes. If your product is not designed to operate in FIPS mode, the task will identify that and will
automatically skip the FIPS scan. However, the task still needs to be a part of your pipeline.
* This commit adds the fbc-fips-check task to your pipeline yaml.
* It also adds a file named `images-mirror-set.yaml` to your `.tekton` directory with an example in it. This file is an `ImageDigestMirrorSet` required by the task to access any …
> RELEASE BLOCKER(March 1, 2025): add fbc-fips-check task to FBC pipeline

- .tekton/cli-manager-operator-fbc-4-18-pull-request.yaml
- .tekton/cli-manager-operator-fbc-4-18-push.yaml
A new task in the FBC builder pipeline will soon become required by Konflux's Conforma policies.
The task definition can be found here:
- https://github.com/konflux-ci/build-definitions/tree/main/task/fbc-target-index-pruning-check/0.1
Ref:
- https://issues.redhat.com/browse/KONFLUX-3935
- https://issues.redhat.com/browse/CVP-4387
> RELEASE BLOCKER(March 17, 2025): Add fbc-target-index-pruning-check to FBC pipelines

- manifests/cli-manager-operator.clusterserviceversion.yaml
Fixes https://github.com/openshift/cli-manager-operator/issues/694
This operator creates a category only for itself:
> Fix typo in OLM categories: OpenShift Optional

- Dockerfile
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
> chore(KONFLUX-6210): fix and set name and cpe label for cli-manager-operator-4-18
